### ISSUE TITLE
No output from sls deploy -v

### ISSUE THREAD

**Issue by EddieEldridge** [CircleCI-Public/serverless-framework-orb#37]
**serverless-framework: circleci/serverless-framework@2.0**

```yaml
jobs:
  # # # # # # # # # # #
  #      BACKEND      #
  # # # # # # # # # # #
  deploy-backend:
      executor: serverless-framework/default
      steps:
        - checkout
        - aws-cli/setup
        - serverless-framework/setup
        - run:
            name: cd backend
            command: cd backend
        - run:
            name: deploy-backend
            command: sls deploy -v
 ```
 
 
![image](https://user-images.githubusercontent.com/22448079/178731872-80cd9b24-a94b-45f4-bd83-cc4e5e9e3c9f.png)

I would expect there to be some output here. Why isn't there any? What steps should I take?
