### ISSUE TITLE
SERVERLESS_ACCESS_KEY Should not be Required / Message Reports this as "Error"

### ISSUE THREAD

**Issue by colinbjohnson** [CircleCI-Public/serverless-framework-orb#49]
**Orb Version**

2.0.1

**Describe the bug**

If the value `SERVERLESS_ACCESS_KEY` is not set the following error is thrown:

```
Error: The environment variable SERVERLESS_ACCESS_KEY is empty.
Please create your serverless dashboard access key and add it to this project as a project environment variable or via contexts.
https://serverless.com/framework/docs/dashboard/cicd/running-in-your-own-cicd#configure-environment-variables
```

**To Reproduce**

Create a CircleCI file similar to the following and run:

```
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.2
  serverless-framework: circleci/serverless-framework@2.0.1
jobs:
  deploy:
    executor: serverless-framework/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
workflows:
  deploy:
    jobs:
      - deploy
```

**Expected behavior**

I would expect a message more similar to the following:

```
INFO: The environment variable SERVERLESS_ACCESS_KEY is not set. This is required If you wish to utilize Serverless' dashboard functionality. You can create your serverless dashboard access key and add it as project environment variable or via a context.
https://serverless.com/framework/docs/dashboard/cicd/running-in-your-own-cicd#configure-environment-variables
```

**Additional context**

It has been my experience that a fair number of serverless users confuse the paid and free serverless offerings. My hope is that this change in language can help serverless users untangle this.
