### ISSUE TITLE
Examples in Documentation Fail to Deploy - Issue is "-v" prints version and exits

### ISSUE THREAD

**Issue by colinbjohnson** [CircleCI-Public/serverless-framework-orb#50]
**Orb Version**
The version number of the orb

2.0.1

**Describe the bug**

Examples in documentation suggest running the following which actually returns the _version_ number of serverless instead of actually deploying. From the serverless manual:

```
cjohnson@cjohnson10 cloudavail % serverless deploy --help
deploy                          Deploy a Serverless service
deploy function                 Deploy a single function from the service
deploy list                     List deployed version of your Serverless Service
deploy list functions           List all the deployed functions and their versions
--conceal                       Hide secrets from the output (e.g. API Gateway key values)
--package / -p                  Path of the deployment package
--force                         Forces a deployment to take place
--aws-s3-accelerate             Enables S3 Transfer Acceleration making uploading artifacts much faster.
--enforce-hash-update           Enforces new function version by overriding descriptions across all your functions. To be used only when migrating to new hashing algorithm.
--region / -r                   Region of the service
--aws-profile                   AWS profile to use with the command
--app                           Dashboard app
--org                           Dashboard org
--use-local-credentials         Rely on locally resolved AWS credentials instead of loading them from Dashboard provider settings (applies only to services integrated with Dashboard)
--config / -c                   Path to serverless config file
--stage / -s                    Stage of the service
--param                         Pass custom parameter values for "param" variable source (usage: --param="key=value")
--help / -h                     Show this message
--version / -v                  Show version info
--verbose                       Show verbose logs
--debug                         Namespace of debug logs to expose (use "*" to display all)
```

And the example from serverless-framework-orb documentation:

```
version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
  serverless-framework: circleci/serverless-framework@2.0
jobs:
  deploy:
    executor: serverless-framework/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          command: serverless deploy -v
          name: deploy
```

**To Reproduce**

NA

**Expected behavior**

I would expect the examples to work properly.

**Additional context**
